-- El Coach con el plan completo. Fase 6b de docs/disenos/2026-09-24-coach-plan-completo.md.
--
-- plan_documentos: los documentos del plan de Chaumer que el Coach lee enteros (reglas con sus
--   condiciones, parámetros, glosario, checklist diaria y contextualización). Los escribe SOLO
--   scripts/plan/sincronizar.mjs desde chaumer/01_Plan (que edita Cowork); nunca a mano. Viven
--   aquí porque la app no puede leer chaumer/ (GitHub Pages no lo publica).
-- coach_uso: una fila por llamada del Coach a Claude, con el consumo de tokens y su coste. Para
--   comprobar que la caché funciona y saber lo que cuesta. No guarda texto de la conversación.

create table if not exists plan_documentos (
  nombre      text primary key check (nombre in ('reglas','parametros','glosario','checklist','contextualizacion')),
  contenido   text not null,
  huella      text not null,             -- sha256 del contenido, para saber si cambió
  origen      text not null,             -- archivo de chaumer/01_Plan del que sale
  actualizado timestamptz not null default now()
);
comment on table plan_documentos is
  'Documentos del plan de Chaumer para el Coach. Los escribe solo scripts/plan/sincronizar.mjs; el texto se edita en chaumer/01_Plan (Cowork).';

create table if not exists coach_uso (
  id              bigint generated by default as identity primary key,
  creado          timestamptz not null default now(),
  fecha_analizada date,
  etapa           smallint,
  modelo          text not null,
  entrada         integer not null default 0,   -- tokens de entrada sin caché
  cache_escrita   integer not null default 0,
  cache_leida     integer not null default 0,
  salida          integer not null default 0,   -- incluye el razonamiento
  coste_usd       numeric(10,4),
  stop_reason     text
);
comment on table coach_uso is
  'Consumo de cada llamada del Coach a Claude (usage de la respuesta). Sin texto de la conversación.';

alter table plan_documentos enable row level security;
drop policy if exists auth_all on plan_documentos;
create policy auth_all on plan_documentos for all to authenticated using (true) with check (true);
grant select, insert, update, delete on plan_documentos to authenticated, service_role;

alter table coach_uso enable row level security;
drop policy if exists auth_all on coach_uso;
create policy auth_all on coach_uso for all to authenticated using (true) with check (true);
grant select, insert, update, delete on coach_uso to authenticated, service_role;

notify pgrst, 'reload schema';
