-- ─────────────────────────────────────────────────────────────────────────
-- Fase 2 Apex: trades individuales de cuentas de evaluación (auto-export NT8)
-- Tabla separada de `trades` (que es la PA real) para no mezclar dinero real
-- con evaluación. El indicador postea aquí cuando "Cuenta de evaluación Apex"
-- está marcado. La app deriva los días (P&L, balance, threshold) desde aquí.
-- Correr en Supabase SQL Editor.
-- ─────────────────────────────────────────────────────────────────────────

create table if not exists apex_trades (
  id           bigint generated by default as identity primary key,
  account      text not null,           -- nombre de cuenta NT, ej "APEX-232411-11"
  instrument   text,                    -- ej "NQ 06-26" / "MNQ 06-26"
  market_pos   text,                    -- Long / Short
  qty          int,
  entry_price  numeric,
  exit_price   numeric,
  entry_time   text,                    -- HH:mm:ss
  exit_time    text,
  exit_name    text,
  profit       numeric not null default 0,   -- NETO (comisión round-trip descontada)
  commission   numeric default 0,
  mae          numeric,                 -- $ máxima excursión adversa
  mfe          numeric,                 -- $ máxima excursión favorable (pico intradía)
  etd          numeric,
  bars         int,
  trade_date   date not null,
  resultado    text,                    -- target / stop / otro
  created_at   timestamptz default now()
);

create index if not exists apex_trades_cuenta_fecha
  on apex_trades (account, trade_date);

alter table apex_trades disable row level security;
grant select, insert, update, delete on apex_trades to anon;
grant usage, select on all sequences in schema public to anon;
