-- La etapa del plan de Chaumer. Fase 5b de docs/disenos/2026-09-24-etapa-plan-chaumer.md.
--
-- 1. `plan_bloque`: el bloque de la checklist (o la categoría del plan) de cada fila,
--    para enseñar el plan agrupado en Estrategia.
-- 2. Etapas: la 1 se cierra el 23/09 y la 2 (Plan de Chaumer) empieza el 24/09. Decisión
--    de Kris: el trade de hoy es el piloto. Las 17 casillas viejas del 24/09 se quedan en
--    la base y dejan de contar (un día es de una sola etapa).
-- 3. Las reglas del plan: SQL generado por scripts/plan/sincronizar.mjs (no editar a mano):
--    40 reglas, 48 líneas de la checklist diaria (2 casillas, 5 automáticas, 41 guía) y 2
--    automáticas que salen de reglas (R-02 ventana horaria, R-04 un contrato).
-- 4. Las 17 casillas de la etapa 1 pasan a activa = false: dejan de verse para marcar en el
--    Diario y en NinjaTrader, y SIGUEN contando en la etapa 1 (la disciplina mira `etapa`).

alter table catalogo_reglas add column if not exists plan_bloque text;
comment on column catalogo_reglas.plan_bloque is
  'Bloque de la checklist diaria del plan (o categoría de la regla) de donde sale la fila. Solo en origen plan_*.';

update disciplina_etapas set hasta = '2026-09-23' where id = 1;
insert into disciplina_etapas (id, nombre, desde, hasta, descripcion) values
  (2, 'Plan de Chaumer', '2026-09-24', null,
   'El checklist sacado del plan de Chaumer (chaumer/01_Plan): 2 casillas y 7 automáticas.')
on conflict (id) do nothing;

insert into catalogo_reglas (codigo, titulo, enunciado, capa, tipo, fase, setup, es_checklist, orden, evidencia, bloquea_go, aplica_si, plan_reglas, origen, plan_tipo, plan_bloque, campo, estado, activa, etapa) values
  ('R-01', 'Analiza, marca zonas y ejecuta TODO sobre MNQ. Un solo grafico.', 'Analiza, marca zonas y ejecuta TODO sobre MNQ. Un solo grafico.', 'plan', 'dura', null, null, false, 1, null, false, 'siempre', array['R-01']::text[], 'plan_regla', null, 'Perímetro operativo', null, 'vigente', true, 2),
  ('R-02', 'Opera unicamente durante los 120 minutos siguientes a la apertura de la sesion americana.', 'Opera unicamente durante los 120 minutos siguientes a la apertura de la sesion americana.', 'plan', 'dura', null, null, false, 2, null, false, 'siempre', array['R-02']::text[], 'plan_regla', null, 'Perímetro operativo', null, 'vigente', true, 2),
  ('R-03', 'Opera con un grafico limpio: velas de 1 minuto y volumen, nada mas.', 'Opera con un grafico limpio: velas de 1 minuto y volumen, nada mas.', 'plan', 'dura', null, null, false, 3, null, false, 'siempre', array['R-03']::text[], 'plan_regla', null, 'Perímetro operativo', null, 'vigente', true, 2),
  ('R-04', 'Opera siempre 1 contrato MNQ. El tamano no cambia por capital, racha ni conviccion.', 'Opera siempre 1 contrato MNQ. El tamano no cambia por capital, racha ni conviccion.', 'plan', 'dura', null, null, false, 4, null, false, 'siempre', array['R-04']::text[], 'plan_regla', null, 'Perímetro operativo', null, 'vigente', true, 2),
  ('R-05', 'Una corrida (= impulso) es la secuencia de velas que arranca cuando una vela supera el extremo de la anterior y termina en la primera vela que retrocede al menos 1 tick contra ella.', 'Una corrida (= impulso) es la secuencia de velas que arranca cuando una vela supera el extremo de la anterior y termina en la primera vela que retrocede al menos 1 tick contra ella.', 'plan', 'dura', null, null, false, 5, null, false, 'siempre', array['R-05']::text[], 'plan_regla', null, 'Estructura del precio', null, 'vigente', true, 2),
  ('R-06', 'El retroceso es la secuencia de velas que arranca en la vela que mata la corrida y termina cuando nace la siguiente corrida.', 'El retroceso es la secuencia de velas que arranca en la vela que mata la corrida y termina cuando nace la siguiente corrida.', 'plan', 'dura', null, null, false, 6, null, false, 'siempre', array['R-06']::text[], 'plan_regla', null, 'Estructura del precio', null, 'vigente', true, 2),
  ('R-07', 'La vela de las 08:31 declara la direccion inicial de la sesion con su propio cuerpo y es la vela origen.', 'La vela de las 08:31 declara la direccion inicial de la sesion con su propio cuerpo y es la vela origen.', 'plan', 'dura', null, null, false, 7, null, false, 'siempre', array['R-07']::text[], 'plan_regla', null, 'Estructura del precio', null, 'vigente', true, 2),
  ('R-08', 'Vela con maximo mayor y minimo menor sin corrida viva: pasa a ser la nueva vela origen y la direccion la da la siguiente.', 'Vela con maximo mayor y minimo menor sin corrida viva: pasa a ser la nueva vela origen y la direccion la da la siguiente.', 'plan', 'dura', null, null, false, 8, null, false, 'siempre', array['R-08']::text[], 'plan_regla', null, 'Estructura del precio', null, 'vigente', true, 2),
  ('R-09', 'Marca la zona sobre la vela designada, desde el borde de su cuerpo hasta el extremo de su mecha, y extiendela hacia la derecha.', 'Marca la zona sobre la vela designada, desde el borde de su cuerpo hasta el extremo de su mecha, y extiendela hacia la derecha.', 'plan', 'dura', null, null, false, 9, null, false, 'siempre', array['R-09']::text[], 'plan_regla', null, 'Zonas', null, 'vigente', true, 2),
  ('R-10', 'Estirar la zona, rompimiento con mecha sin consecucion. El precio rompe una zona con mecha —el cierre se queda dentro— y la consecucion no llega. La zona se extiende hasta la punta de esa mecha: si es una RESISTENCIA se estira solo por arriba; si es un SOPORTE, solo por abajo.', 'Estirar la zona, rompimiento con mecha sin consecucion. El precio rompe una zona con mecha —el cierre se queda dentro— y la consecucion no llega. La zona se extiende hasta la punta de esa mecha: si es una RESISTENCIA se estira solo por arriba; si es un SOPORTE, solo por abajo.', 'plan', 'dura', null, null, false, 10, null, false, 'siempre', array['R-10']::text[], 'plan_regla', null, 'Zonas', null, 'vigente', true, 2),
  ('R-11', 'Zona apendice, rompimiento con cuerpo sin consecucion. El precio rompe una zona CON CUERPO —el cierre queda fuera— y la consecucion no llega. La zona original no se toca y nace una SEGUNDA zona sobre la mecha de la vela de rompimiento: un borde es el borde del cuerpo de esa vela, el otro es la punta de su mecha.', 'Zona apendice, rompimiento con cuerpo sin consecucion. El precio rompe una zona CON CUERPO —el cierre queda fuera— y la consecucion no llega. La zona original no se toca y nace una SEGUNDA zona sobre la mecha de la vela de rompimiento: un borde es el borde del cuerpo de esa vela, el otro es la punta de su mecha.', 'plan', 'dura', null, null, false, 11, null, false, 'siempre', array['R-11']::text[], 'plan_regla', null, 'Zonas', null, 'vigente', true, 2),
  ('R-12', 'Marca una zona entre dos zonas solo si el movimiento que la genera queda entero dentro de la mitad en la que empezo.', 'Marca una zona entre dos zonas solo si el movimiento que la genera queda entero dentro de la mitad en la que empezo.', 'plan', 'dura', null, null, false, 12, null, false, 'siempre', array['R-12']::text[], 'plan_regla', null, 'Zonas', null, 'vigente', true, 2),
  ('R-13', 'Si la zona que ibas a marcar toca una existente, no marques una nueva: estira la existente.', 'Si la zona que ibas a marcar toca una existente, no marques una nueva: estira la existente.', 'plan', 'dura', null, null, false, 13, null, false, 'siempre', array['R-13']::text[], 'plan_regla', null, 'Zonas', null, 'vigente', true, 2),
  ('R-14', 'El plazo de 5 velas es un TOPE, no una espera obligatoria: si antes el mercado arma una estructura completa en sentido contrario al rompimiento, la geometria se resuelve en ese momento.', 'El plazo de 5 velas es un TOPE, no una espera obligatoria: si antes el mercado arma una estructura completa en sentido contrario al rompimiento, la geometria se resuelve en ese momento.', 'plan', 'dura', null, null, false, 14, null, false, 'siempre', array['R-14']::text[], 'plan_regla', null, 'Zonas', null, 'vigente', true, 2),
  ('R-15', 'En la ventana de premercado (19:00 hora Colombia del dia anterior hasta la apertura americana), marca zona sobre TODA vela cuyo volumen supere el umbral. Fuera de esa ventana la regla no aplica.', 'En la ventana de premercado (19:00 hora Colombia del dia anterior hasta la apertura americana), marca zona sobre TODA vela cuyo volumen supere el umbral. Fuera de esa ventana la regla no aplica.', 'plan', 'dura', null, null, false, 15, null, false, 'siempre', array['R-15']::text[], 'plan_regla', null, 'Zonas', null, 'vigente', true, 2),
  ('R-16', 'La zona de la corrida se marca al aparecer el retroceso; la del retroceso solo cuando el retroceso queda confirmado. Antes es solo una linea provisional.', 'La zona de la corrida se marca al aparecer el retroceso; la del retroceso solo cuando el retroceso queda confirmado. Antes es solo una linea provisional.', 'plan', 'dura', null, null, false, 16, null, false, 'siempre', array['R-16']::text[], 'plan_regla', null, 'Zonas', null, 'vigente', true, 2),
  ('R-17', 'Dentro de una banda entre dos zonas se marca como maximo una zona en toda la jornada, y es la del primer retroceso.', 'Dentro de una banda entre dos zonas se marca como maximo una zona en toda la jornada, y es la del primer retroceso.', 'plan', 'dura', null, null, false, 17, null, false, 'siempre', array['R-17']::text[], 'plan_regla', null, 'Zonas', null, 'vigente', true, 2),
  ('R-18', 'Salir de una zona o de una banda es rompimiento mas consecucion, no geometria.', 'Salir de una zona o de una banda es rompimiento mas consecucion, no geometria.', 'plan', 'dura', null, null, false, 18, null, false, 'siempre', array['R-18']::text[], 'plan_regla', null, 'Zonas', null, 'vigente', true, 2),
  ('R-19', 'Seis precisiones de dibujo de zonas.', 'Seis precisiones de dibujo de zonas.', 'plan', 'dura', null, null, false, 19, null, false, 'siempre', array['R-19']::text[], 'plan_regla', null, 'Zonas', null, 'vigente', true, 2),
  ('R-20', 'Rompimiento es superar el borde de la zona por al menos un tick; consecucion es superar por un tick el extremo de la vela de rompimiento. La consecucion que TRASPASA una zona no tiene plazo.', 'Rompimiento es superar el borde de la zona por al menos un tick; consecucion es superar por un tick el extremo de la vela de rompimiento. La consecucion que TRASPASA una zona no tiene plazo.', 'plan', 'dura', null, null, false, 20, null, false, 'siempre', array['R-20']::text[], 'plan_regla', null, 'Zonas', null, 'vigente', true, 2),
  ('R-21', 'Una zona deja de tener efecto cuando ha sido superada en las dos direcciones.', 'Una zona deja de tener efecto cuando ha sido superada en las dos direcciones.', 'plan', 'dura', null, null, false, 21, null, false, 'siempre', array['R-21']::text[], 'plan_regla', null, 'Zonas', null, 'vigente', true, 2),
  ('R-22', 'La vela que confirma un traspaso no abre a la vez el rompimiento del lado contrario.', 'La vela que confirma un traspaso no abre a la vez el rompimiento del lado contrario.', 'plan', 'dura', null, null, false, 22, null, false, 'siempre', array['R-22']::text[], 'plan_regla', null, 'Zonas', null, 'vigente', true, 2),
  ('R-23', 'Toma el primer setup valido cuya orden se llene.', 'Toma el primer setup valido cuya orden se llene.', 'plan', 'dura', null, null, false, 23, null, false, 'siempre', array['R-23']::text[], 'plan_regla', null, 'Setup y entrada', null, 'vigente', true, 2),
  ('R-24', 'Entra siempre con orden stop en reposo colocada al cierre de la vela de rompimiento.', 'Entra siempre con orden stop en reposo colocada al cierre de la vela de rompimiento.', 'plan', 'dura', null, null, false, 24, null, false, 'siempre', array['R-24']::text[], 'plan_regla', null, 'Setup y entrada', null, 'vigente', true, 2),
  ('R-25', 'Setup Continuacion: un IRI —corrida, retroceso, zona y rompimiento de esa zona— y su consecucion. La consecucion es la entrada.', 'Setup Continuacion: un IRI —corrida, retroceso, zona y rompimiento de esa zona— y su consecucion. La consecucion es la entrada.', 'plan', 'dura', null, null, false, 25, null, false, 'siempre', array['R-25']::text[], 'plan_regla', null, 'Setup y entrada', null, 'vigente', true, 2),
  ('R-26', 'Setup Reingreso: tras un rompimiento con consecucion que falla, el precio recupera la zona entera y se opera en sentido contrario.', 'Setup Reingreso: tras un rompimiento con consecucion que falla, el precio recupera la zona entera y se opera en sentido contrario.', 'plan', 'dura', null, null, false, 26, null, false, 'siempre', array['R-26']::text[], 'plan_regla', null, 'Setup y entrada', null, 'vigente', true, 2),
  ('R-27', 'La direccion de la vela de las 08:31 marca por donde empieza el dia pero no obliga a operar en ese sentido toda la sesion.', 'La direccion de la vela de las 08:31 marca por donde empieza el dia pero no obliga a operar en ese sentido toda la sesion.', 'plan', 'dura', null, null, false, 27, null, false, 'siempre', array['R-27']::text[], 'plan_regla', null, 'Setup y entrada', null, 'vigente', true, 2),
  ('R-40', 'Corrida fluida: solo se entra en el rompimiento de la zona de una corrida FLUIDA. La secuencia tiene que salir bien tres veces seguidas: corrida, retroceso que no se pasa, y corrida siguiente que rompe la zona.', 'Corrida fluida: solo se entra en el rompimiento de la zona de una corrida FLUIDA. La secuencia tiene que salir bien tres veces seguidas: corrida, retroceso que no se pasa, y corrida siguiente que rompe la zona.', 'plan', 'dura', null, null, false, 28, null, false, 'siempre', array['R-40']::text[], 'plan_regla', null, 'Setup y entrada', null, 'vigente', true, 2),
  ('R-41', 'Punto de referencia: el objetivo de un REINGRESO no puede pasar del nivel de referencia de un retroceso anterior que siga vivo. Solo aplica al reingreso.', 'Punto de referencia: el objetivo de un REINGRESO no puede pasar del nivel de referencia de un retroceso anterior que siga vivo. Solo aplica al reingreso.', 'plan', 'dura', null, null, false, 29, null, false, 'siempre', array['R-41']::text[], 'plan_regla', null, 'Setup y entrada', null, 'vigente', true, 2),
  ('R-28', 'Ejecuta como maximo una operacion por sesion.', 'Ejecuta como maximo una operacion por sesion.', 'plan', 'dura', null, null, false, 30, null, false, 'siempre', array['R-28']::text[], 'plan_regla', null, 'Riesgo, orden y gestión', null, 'vigente', true, 2),
  ('R-29', 'Manten la orden pendiente hasta que se llene, hasta que se agoten 5 velas sin consecucion, hasta que el precio vuelva al punto del stop, o hasta el fin de la ventana.', 'Manten la orden pendiente hasta que se llene, hasta que se agoten 5 velas sin consecucion, hasta que el precio vuelva al punto del stop, o hasta el fin de la ventana.', 'plan', 'dura', null, null, false, 31, null, false, 'siempre', array['R-29']::text[], 'plan_regla', null, 'Riesgo, orden y gestión', null, 'vigente', true, 2),
  ('R-30', 'Una operacion abierta se gestiona hasta stop o target, aunque termine la ventana operativa.', 'Una operacion abierta se gestiona hasta stop o target, aunque termine la ventana operativa.', 'plan', 'dura', null, null, false, 32, null, false, 'siempre', array['R-30']::text[], 'plan_regla', null, 'Riesgo, orden y gestión', null, 'vigente', true, 2),
  ('R-31', 'Ejecuta con la ATM K1 al valor de ATM_DEFECTO y ajusta stop y target a mano tras el llenado, en ese orden.', 'Ejecuta con la ATM K1 al valor de ATM_DEFECTO y ajusta stop y target a mano tras el llenado, en ese orden.', 'plan', 'dura', null, null, false, 33, null, false, 'siempre', array['R-31']::text[], 'plan_regla', null, 'Riesgo, orden y gestión', null, 'vigente', true, 2),
  ('R-32', 'Ancla la regla en el nivel de entrada, mide el stop hasta su referencia estructural y pon el target a esa misma distancia.', 'Ancla la regla en el nivel de entrada, mide el stop hasta su referencia estructural y pon el target a esa misma distancia.', 'plan', 'dura', null, null, false, 34, null, false, 'siempre', array['R-32']::text[], 'plan_regla', null, 'Riesgo, orden y gestión', null, 'vigente', true, 2),
  ('R-33', 'Una vez ajustados stop y target, NO se gestiona la posicion. Nunca.', 'Una vez ajustados stop y target, NO se gestiona la posicion. Nunca.', 'plan', 'dura', null, null, false, 35, null, false, 'siempre', array['R-33']::text[], 'plan_regla', null, 'Riesgo, orden y gestión', null, 'vigente', true, 2),
  ('R-34', 'Al llenarse la orden termina el ANALISIS del dia, no solo la operativa.', 'Al llenarse la orden termina el ANALISIS del dia, no solo la operativa.', 'plan', 'dura', null, null, false, 36, null, false, 'siempre', array['R-34']::text[], 'plan_regla', null, 'Riesgo, orden y gestión', null, 'vigente', true, 2),
  ('R-35', 'No operes en la ventana de +/-5 minutos alrededor de una noticia roja de Forex Factory.', 'No operes en la ventana de +/-5 minutos alrededor de una noticia roja de Forex Factory.', 'plan', 'dura', null, null, false, 37, null, false, 'siempre', array['R-35']::text[], 'plan_regla', null, 'Filtros de no-operar', null, 'vigente', true, 2),
  ('R-36', 'En dia de FOMC no se opera Continuacion. Solo se permite Reingreso.', 'En dia de FOMC no se opera Continuacion. Solo se permite Reingreso.', 'plan', 'dura', null, null, false, 38, null, false, 'siempre', array['R-36']::text[], 'plan_regla', null, 'Filtros de no-operar', null, 'vigente', true, 2),
  ('R-37', 'No se opera estando enfermo o sin encontrarse bien mentalmente.', 'No se opera estando enfermo o sin encontrarse bien mentalmente.', 'plan', 'dura', null, null, false, 39, null, false, 'siempre', array['R-37']::text[], 'plan_regla', null, 'Filtros de no-operar', null, 'vigente', true, 2),
  ('R-38', 'Ejecuta la sesion siguiendo la checklist diaria en orden, y registra TODAS las sesiones, incluidas aquellas en que no se opero.', 'Ejecuta la sesion siguiendo la checklist diaria en orden, y registra TODAS las sesiones, incluidas aquellas en que no se opero.', 'plan', 'dura', null, null, false, 40, null, false, 'siempre', array['R-38']::text[], 'plan_regla', null, 'Proceso diario', null, 'vigente', true, 2),
  ('p2_g_7ca8fa6a', '¿Estoy bien, física y mentalmente? — NO → no se opera hoy. Se cierra aquí', '¿Estoy bien, física y mentalmente? — NO → no se opera hoy. Se cierra aquí', 'plan', 'blanda', null, null, false, 101, null, false, 'siempre', array['R-37']::text[], 'plan_linea', 'guia', '🅰 ANTES DE ABRIR NINJATRADER', null, 'vigente', true, 2),
  ('p2_g_56e12136', 'Forex Factory: ¿hay evento de la Fed en rojo hoy? — SÍ → hoy solo Reingreso. Continuación prohibida todo el día', 'Forex Factory: ¿hay evento de la Fed en rojo hoy? — SÍ → hoy solo Reingreso. Continuación prohibida todo el día', 'plan', 'blanda', null, null, false, 102, null, false, 'siempre', array['R-36']::text[], 'plan_linea', 'guia', '🅰 ANTES DE ABRIR NINJATRADER', null, 'vigente', true, 2),
  ('p2_g_c2fe2169', 'Forex Factory: anotar la hora de cada noticia roja — —', 'Forex Factory: anotar la hora de cada noticia roja — —', 'plan', 'blanda', null, null, false, 103, null, false, 'siempre', array['R-35']::text[], 'plan_linea', 'guia', '🅰 ANTES DE ABRIR NINJATRADER', null, 'vigente', true, 2),
  ('p2_g_3c6db45c', 'Calcular las ventanas T−5 → T+5 y marcar las que caigan dentro de la ventana operativa — —', 'Calcular las ventanas T−5 → T+5 y marcar las que caigan dentro de la ventana operativa — —', 'plan', 'blanda', null, null, false, 104, null, false, 'siempre', array['R-35']::text[], 'plan_linea', 'guia', '🅰 ANTES DE ABRIR NINJATRADER', null, 'vigente', true, 2),
  ('p2_g_d5a65697', 'Gráfico abierto: MNQ, 1 minuto, único indicador Volume Up Down', 'Gráfico abierto: MNQ, 1 minuto, único indicador Volume Up Down', 'plan', 'blanda', null, null, false, 105, null, false, 'siempre', array['R-03','R-01']::text[], 'plan_linea', 'guia', '🅱 PREMERCADO · desde las 19:00 hora Colombia del día anterior', null, 'vigente', true, 2),
  ('p2_g_954acdc6', 'Escanear desde 19:00 Col (apertura de Tokio) hasta la apertura americana', 'Escanear desde 19:00 Col (apertura de Tokio) hasta la apertura americana', 'plan', 'blanda', null, null, false, 106, null, false, 'siempre', array['R-15']::text[], 'plan_linea', 'guia', '🅱 PREMERCADO · desde las 19:00 hora Colombia del día anterior', null, 'vigente', true, 2),
  ('p2_g_f322eb01', 'Toda vela que supere el umbral de volumen → marcar zona. Alcista → resistencia · Bajista → soporte', 'Toda vela que supere el umbral de volumen → marcar zona. Alcista → resistencia · Bajista → soporte', 'plan', 'blanda', null, null, false, 107, null, false, 'siempre', array['R-15']::text[], 'plan_linea', 'guia', '🅱 PREMERCADO · desde las 19:00 hora Colombia del día anterior', null, 'vigente', true, 2),
  ('p2_g_bdc4380f', '⚠️ Mirar el umbral vigente en PARAMETROS.md antes de empezar. Hoy son más de 8.000 contratos en MNQ (desde el 14/09/2026). Es un parámetro ajustable, y no se cambia con la sesión empezada', '⚠️ Mirar el umbral vigente en PARAMETROS.md antes de empezar. Hoy son más de 8.000 contratos en MNQ (desde el 14/09/2026). Es un parámetro ajustable, y no se cambia con la sesión empezada', 'plan', 'blanda', null, null, false, 108, null, false, 'siempre', array['R-15']::text[], 'plan_linea', 'guia', '🅱 PREMERCADO · desde las 19:00 hora Colombia del día anterior', null, 'vigente', true, 2),
  ('p2_g_88dfc66e', 'Se marcan todas las que superen el umbral, no solo los extremos', 'Se marcan todas las que superen el umbral, no solo los extremos', 'plan', 'blanda', null, null, false, 109, null, false, 'siempre', array['R-15']::text[], 'plan_linea', 'guia', '🅱 PREMERCADO · desde las 19:00 hora Colombia del día anterior', null, 'vigente', true, 2),
  ('p2_g_ad8984a6', 'Límites de cada zona: del borde del cuerpo a la punta de la mecha', 'Límites de cada zona: del borde del cuerpo a la punta de la mecha', 'plan', 'blanda', null, null, false, 110, null, false, 'siempre', array['R-09']::text[], 'plan_linea', 'guia', '🅱 PREMERCADO · desde las 19:00 hora Colombia del día anterior', null, 'vigente', true, 2),
  ('p2_g_05dcd39d', 'Si una zona candidata toca otra existente → estirar la existente, no crear una nueva', 'Si una zona candidata toca otra existente → estirar la existente, no crear una nueva', 'plan', 'blanda', null, null, false, 111, null, false, 'siempre', array['R-13']::text[], 'plan_linea', 'guia', '🅱 PREMERCADO · desde las 19:00 hora Colombia del día anterior', null, 'vigente', true, 2),
  ('p2_g_32e3a881', 'Zona entre dos zonas: solo si el movimiento no cruza el 50 % entre bordes internos', 'Zona entre dos zonas: solo si el movimiento no cruza el 50 % entre bordes internos', 'plan', 'blanda', null, null, false, 112, null, false, 'siempre', array['R-12']::text[], 'plan_linea', 'guia', '🅱 PREMERCADO · desde las 19:00 hora Colombia del día anterior', null, 'vigente', true, 2),
  ('p2_g_509ccd8b', 'Primer setup válido. No se compara con posibles setups posteriores ni se espera uno mejor', 'Primer setup válido. No se compara con posibles setups posteriores ni se espera uno mejor', 'plan', 'blanda', null, null, false, 113, null, false, 'siempre', array['R-23']::text[], 'plan_linea', 'guia', '🅲 VENTANA OPERATIVA · 08:30–10:30 Col (verano) · 09:30–11:30 Col (invierno) · Identificar', null, 'vigente', true, 2),
  ('p2_g_882c476d', '¿Es Continuación o Reingreso?', '¿Es Continuación o Reingreso?', 'plan', 'blanda', null, null, false, 114, null, false, 'siempre', array['R-25','R-26']::text[], 'plan_linea', 'guia', '🅲 VENTANA OPERATIVA · 08:30–10:30 Col (verano) · 09:30–11:30 Col (invierno) · Identificar', null, 'vigente', true, 2),
  ('p2_corrida_fluida', '¿La corrida es FLUIDA? Tres cosas seguidas: la corrida dejó su zona · el retroceso no se pasó (mide menos que su corrida) · y ésta es la corrida siguiente, que la rompe. Cada corrida se empareja con el retroceso que viene justo después de ella', '¿La corrida es FLUIDA? Tres cosas seguidas: la corrida dejó su zona · el retroceso no se pasó (mide menos que su corrida) · y ésta es la corrida siguiente, que la rompe. Cada corrida se empareja con el retroceso que viene justo después de ella', 'proceso', 'dura', 2, 'continuacion', true, 1, 'declarada', true, 'siempre', array['R-40']::text[], 'plan_linea', 'casilla', '🅲 VENTANA OPERATIVA · 08:30–10:30 Col (verano) · 09:30–11:30 Col (invierno) · Identificar', null, 'vigente', true, 2),
  ('p2_g_3891b80b', 'Continuación — extremo del retroceso', 'Continuación — extremo del retroceso', 'plan', 'blanda', null, null, false, 116, null, false, 'siempre', array['R-32']::text[], 'plan_linea', 'guia', '🅲 VENTANA OPERATIVA · 08:30–10:30 Col (verano) · 09:30–11:30 Col (invierno) · Medir · anclar la regla en el nivel de entrada', null, 'vigente', true, 2),
  ('p2_g_a82d169d', 'Reingreso — extremo de la corrida fallida', 'Reingreso — extremo de la corrida fallida', 'plan', 'blanda', null, null, false, 117, null, false, 'siempre', array['R-32']::text[], 'plan_linea', 'guia', '🅲 VENTANA OPERATIVA · 08:30–10:30 Col (verano) · 09:30–11:30 Col (invierno) · Medir · anclar la regla en el nivel de entrada', null, 'vigente', true, 2),
  ('p2_g_fad99fde', 'Target = misma distancia, al otro lado. 1:1', 'Target = misma distancia, al otro lado. 1:1', 'plan', 'blanda', null, null, false, 118, null, false, 'siempre', array['R-32']::text[], 'plan_linea', 'guia', '🅲 VENTANA OPERATIVA · 08:30–10:30 Col (verano) · 09:30–11:30 Col (invierno) · Medir · anclar la regla en el nivel de entrada', null, 'vigente', true, 2),
  ('p2_stop_max', 'Stop ≤ 80 puntos (STOP_MAX) — NO SE OPERA', 'Stop ≤ 80 puntos (STOP_MAX) — NO SE OPERA', 'proceso', 'dura', 2, null, true, 3, 'auto', false, 'siempre', array['R-31']::text[], 'plan_linea', 'auto', '🅲 VENTANA OPERATIVA · 08:30–10:30 Col (verano) · 09:30–11:30 Col (invierno) · Los filtros · basta que falle uno', 'trades.mae / ($punto x contratos)', 'vigente', true, 2),
  ('p2_g_9e2b60e5', 'Target 1:1 libre de zonas vigentes — NO SE OPERA', 'Target 1:1 libre de zonas vigentes — NO SE OPERA', 'plan', 'blanda', null, null, false, 120, null, false, 'siempre', array['R-32','R-21']::text[], 'plan_linea', 'guia', '🅲 VENTANA OPERATIVA · 08:30–10:30 Col (verano) · 09:30–11:30 Col (invierno) · Los filtros · basta que falle uno', null, 'vigente', true, 2),
  ('p2_punto_referencia', 'Target sin pasar del punto de referencia vivo más cercano que quede entre la entrada y el objetivo — el nivel de referencia de cualquier retroceso. Muere solo cuando una vela CIERRA más allá; la mecha no lo rompe — NO SE OPERA', 'Target sin pasar del punto de referencia vivo más cercano que quede entre la entrada y el objetivo — el nivel de referencia de cualquier retroceso. Muere solo cuando una vela CIERRA más allá; la mecha no lo rompe — NO SE OPERA', 'proceso', 'dura', 2, 'reingreso', true, 2, 'declarada', true, 'siempre', array['R-41','R-26']::text[], 'plan_linea', 'casilla', '🅲 VENTANA OPERATIVA · 08:30–10:30 Col (verano) · 09:30–11:30 Col (invierno) · Los filtros · basta que falle uno', null, 'vigente', true, 2),
  ('p2_g_0525f6f2', '¿La corrida es fluida? — NO SE OPERA ESE ROMPIMIENTO. La zona sigue viva. Se espera a otro IRI que deje una zona nueva entera más allá de ésta — por encima para largo, por debajo para corto', '¿La corrida es fluida? — NO SE OPERA ESE ROMPIMIENTO. La zona sigue viva. Se espera a otro IRI que deje una zona nueva entera más allá de ésta — por encima para largo, por debajo para corto', 'plan', 'blanda', null, null, false, 122, null, false, 'siempre', array['R-40']::text[], 'plan_linea', 'guia', '🅲 VENTANA OPERATIVA · 08:30–10:30 Col (verano) · 09:30–11:30 Col (invierno) · Los filtros · basta que falle uno', null, 'vigente', true, 2),
  ('p2_fomc_continuacion', '¿Es día de FOMC y el setup es una Continuación? — NO SE OPERA', '¿Es día de FOMC y el setup es una Continuación? — NO SE OPERA', 'proceso', 'dura', 2, null, true, 4, 'auto', false, 'dia_fomc', array['R-36']::text[], 'plan_linea', 'auto', '🅲 VENTANA OPERATIVA · 08:30–10:30 Col (verano) · 09:30–11:30 Col (invierno) · Los filtros · basta que falle uno', 'catalogo_fechas.tipo=fomc + familia del setup', 'vigente', true, 2),
  ('p2_noticia', '¿Estoy dentro de una ventana de noticia T−5 → T+5? → no colocar. Si ya hay orden puesta, cancelarla', '¿Estoy dentro de una ventana de noticia T−5 → T+5? → no colocar. Si ya hay orden puesta, cancelarla', 'proceso', 'dura', 3, null, true, 1, 'auto', false, 'hay_noticia', array['R-35']::text[], 'plan_linea', 'auto', '🅲 VENTANA OPERATIVA · 08:30–10:30 Col (verano) · 09:30–11:30 Col (invierno) · Enviar', 'trades.entry_time vs sesion_noticias.hora ±5min', 'vigente', true, 2),
  ('p2_g_8a5d31d2', 'Stop Market al cierre de la vela de rompimiento o de reingreso, 1 tick más allá de su extremo', 'Stop Market al cierre de la vela de rompimiento o de reingreso, 1 tick más allá de su extremo', 'plan', 'blanda', null, null, false, 125, null, false, 'siempre', array['R-24']::text[], 'plan_linea', 'guia', '🅲 VENTANA OPERATIVA · 08:30–10:30 Col (verano) · 09:30–11:30 Col (invierno) · Enviar', null, 'vigente', true, 2),
  ('p2_instrumento', 'La orden se envía sobre el gráfico de MNQ — el único que hay', 'La orden se envía sobre el gráfico de MNQ — el único que hay', 'proceso', 'dura', 3, null, true, 2, 'auto', false, 'siempre', array['R-01','R-24']::text[], 'plan_linea', 'auto', '🅲 VENTANA OPERATIVA · 08:30–10:30 Col (verano) · 09:30–11:30 Col (invierno) · Enviar', 'trades.instrument empieza por MNQ', 'vigente', true, 2),
  ('p2_g_c214cf46', 'No se persigue el precio a mano. Orden a mercado y orden límite: prohibidas', 'No se persigue el precio a mano. Orden a mercado y orden límite: prohibidas', 'plan', 'blanda', null, null, false, 127, null, false, 'siempre', array['R-24']::text[], 'plan_linea', 'guia', '🅲 VENTANA OPERATIVA · 08:30–10:30 Col (verano) · 09:30–11:30 Col (invierno) · Enviar', null, 'vigente', true, 2),
  ('p2_g_ed59f89a', 'Pasan 5 velas desde el rompimiento sin consecución (el precio no llega al nivel de la orden)', 'Pasan 5 velas desde el rompimiento sin consecución (el precio no llega al nivel de la orden)', 'plan', 'blanda', null, null, false, 128, null, false, 'siempre', array['R-29']::text[], 'plan_linea', 'guia', '🅲 VENTANA OPERATIVA · 08:30–10:30 Col (verano) · 09:30–11:30 Col (invierno) · Vigilar la orden pendiente · cancelar con lo primero que llegue', null, 'vigente', true, 2),
  ('p2_g_ed096ec1', 'El precio vuelve al punto del stop — el extremo alcanzado desde que nació la zona (R-32)', 'El precio vuelve al punto del stop — el extremo alcanzado desde que nació la zona (R-32)', 'plan', 'blanda', null, null, false, 129, null, false, 'siempre', array['R-32','R-29']::text[], 'plan_linea', 'guia', '🅲 VENTANA OPERATIVA · 08:30–10:30 Col (verano) · 09:30–11:30 Col (invierno) · Vigilar la orden pendiente · cancelar con lo primero que llegue', null, 'vigente', true, 2),
  ('p2_g_3e1b11b1', 'Son las 11:29 ET', 'Son las 11:29 ET', 'plan', 'blanda', null, null, false, 130, null, false, 'siempre', array['R-29']::text[], 'plan_linea', 'guia', '🅲 VENTANA OPERATIVA · 08:30–10:30 Col (verano) · 09:30–11:30 Col (invierno) · Vigilar la orden pendiente · cancelar con lo primero que llegue', null, 'vigente', true, 2),
  ('p2_g_ec38f419', '⚠️ Un retroceso nuevo NO cancela. La orden sigue viva', '⚠️ Un retroceso nuevo NO cancela. La orden sigue viva', 'plan', 'blanda', null, null, false, 131, null, false, 'siempre', array['R-29']::text[], 'plan_linea', 'guia', '🅲 VENTANA OPERATIVA · 08:30–10:30 Col (verano) · 09:30–11:30 Col (invierno) · Vigilar la orden pendiente · cancelar con lo primero que llegue', null, 'vigente', true, 2),
  ('p2_g_32941671', 'Entra una ventana de noticia roja', 'Entra una ventana de noticia roja', 'plan', 'blanda', null, null, false, 132, null, false, 'siempre', array['R-35']::text[], 'plan_linea', 'guia', '🅲 VENTANA OPERATIVA · 08:30–10:30 Col (verano) · 09:30–11:30 Col (invierno) · Vigilar la orden pendiente · cancelar con lo primero que llegue', null, 'vigente', true, 2),
  ('p2_g_ab1071ef', '1º mover el stop a su nivel estructural', '1º mover el stop a su nivel estructural', 'plan', 'blanda', null, null, false, 133, null, false, 'siempre', array['R-31']::text[], 'plan_linea', 'guia', '🅳 TRAS EL LLENADO', null, 'vigente', true, 2),
  ('p2_g_c71bf461', '2º mover el target a distancia 1:1', '2º mover el target a distancia 1:1', 'plan', 'blanda', null, null, false, 134, null, false, 'siempre', array['R-31','R-32']::text[], 'plan_linea', 'guia', '🅳 TRAS EL LLENADO', null, 'vigente', true, 2),
  ('p2_g_9963d984', '🛑 NO SE TOCA NADA MÁS. JAMÁS. Ni breakeven, ni cierre manual, ni parcial, ni añadir', '🛑 NO SE TOCA NADA MÁS. JAMÁS. Ni breakeven, ni cierre manual, ni parcial, ni añadir', 'plan', 'blanda', null, null, false, 135, null, false, 'siempre', array['R-33']::text[], 'plan_linea', 'guia', '🅳 TRAS EL LLENADO', null, 'vigente', true, 2),
  ('p2_g_218eb551', 'Solo hay dos salidas: stop o target', 'Solo hay dos salidas: stop o target', 'plan', 'blanda', null, null, false, 136, null, false, 'siempre', array['R-33']::text[], 'plan_linea', 'guia', '🅳 TRAS EL LLENADO', null, 'vigente', true, 2),
  ('p2_una_operacion', 'Cupo consumido. No más órdenes hoy, aunque aparezcan setups válidos', 'Cupo consumido. No más órdenes hoy, aunque aparezcan setups válidos', 'proceso', 'dura', 3, null, true, 3, 'auto', false, 'siempre', array['R-28']::text[], 'plan_linea', 'auto', '🅳 TRAS EL LLENADO', 'trades del día ≤ 1', 'vigente', true, 2),
  ('p2_g_47bfb2ed', 'El fin de ventana no obliga a cerrar una posición abierta', 'El fin de ventana no obliga a cerrar una posición abierta', 'plan', 'blanda', null, null, false, 138, null, false, 'siempre', array['R-30']::text[], 'plan_linea', 'guia', '🅳 TRAS EL LLENADO', null, 'vigente', true, 2),
  ('p2_g_411dcd27', '¿La zona candidata cae dentro de una banda ya gastada hoy? → no se marca', '¿La zona candidata cae dentro de una banda ya gastada hoy? → no se marca', 'plan', 'blanda', null, null, false, 139, null, false, 'siempre', array['R-17']::text[], 'plan_linea', 'guia', '🔴 Añadido 27/08/2026 · lo que hay que mirar en cada zona', null, 'vigente', true, 2),
  ('p2_g_a2236380', '¿Hay una zona viva con rompimiento esperando consecución entre el precio y la zona candidata? → no se marca', '¿Hay una zona viva con rompimiento esperando consecución entre el precio y la zona candidata? → no se marca', 'plan', 'blanda', null, null, false, 140, null, false, 'siempre', array['R-18']::text[], 'plan_linea', 'guia', '🔴 Añadido 27/08/2026 · lo que hay que mirar en cada zona', null, 'vigente', true, 2),
  ('p2_g_4d13fb5a', 'El rompimiento se lee por la mecha, no por el cierre', 'El rompimiento se lee por la mecha, no por el cierre', 'plan', 'blanda', null, null, false, 141, null, false, 'siempre', array['R-19']::text[], 'plan_linea', 'guia', '🔴 Añadido 27/08/2026 · lo que hay que mirar en cada zona', null, 'vigente', true, 2),
  ('p2_g_2fbe48dc', 'Una zona no queda inválida hasta que llega la consecución — y esa consecución no tiene plazo', 'Una zona no queda inválida hasta que llega la consecución — y esa consecución no tiene plazo', 'plan', 'blanda', null, null, false, 142, null, false, 'siempre', array['R-20','R-21']::text[], 'plan_linea', 'guia', '🔴 Añadido 27/08/2026 · lo que hay que mirar en cada zona', null, 'vigente', true, 2),
  ('p2_g_7e25f57a', 'La vela que confirma un traspaso no abre el rompimiento contrario: se busca desde la siguiente', 'La vela que confirma un traspaso no abre el rompimiento contrario: se busca desde la siguiente', 'plan', 'blanda', null, null, false, 143, null, false, 'siempre', array['R-22']::text[], 'plan_linea', 'guia', '🔴 Añadido 27/08/2026 · lo que hay que mirar en cada zona', null, 'vigente', true, 2),
  ('p2_g_e84a5159', 'Vencido el plazo sin consecución: mecha → se estira · cuerpo → nace apéndice', 'Vencido el plazo sin consecución: mecha → se estira · cuerpo → nace apéndice', 'plan', 'blanda', null, null, false, 144, null, false, 'siempre', array['R-10','R-11']::text[], 'plan_linea', 'guia', '🔴 Añadido 27/08/2026 · lo que hay que mirar en cada zona', null, 'vigente', true, 2),
  ('p2_g_609eb8eb', 'El rectángulo se dibuja desde la vela origen', 'El rectángulo se dibuja desde la vela origen', 'plan', 'blanda', null, null, false, 145, null, false, 'siempre', array['R-19']::text[], 'plan_linea', 'guia', '🔴 Añadido 27/08/2026 · lo que hay que mirar en cada zona', null, 'vigente', true, 2),
  ('p2_g_230aec35', 'El stop es el extremo alcanzado desde que nació la zona hasta el rompimiento — no solo el del retroceso que la originó', 'El stop es el extremo alcanzado desde que nació la zona hasta el rompimiento — no solo el del retroceso que la originó', 'plan', 'blanda', null, null, false, 146, null, false, 'siempre', array['R-32']::text[], 'plan_linea', 'guia', '🔴 Añadido 27/08/2026 · antes de enviar la orden', null, 'vigente', true, 2),
  ('p2_g_52b219ac', 'Si es Reingreso: ¿el precio ya superó el extremo de la vela de consecución? → no hay reingreso', 'Si es Reingreso: ¿el precio ya superó el extremo de la vela de consecución? → no hay reingreso', 'plan', 'blanda', null, null, false, 147, null, false, 'siempre', array['R-26']::text[], 'plan_linea', 'guia', '🔴 Añadido 27/08/2026 · antes de enviar la orden', null, 'vigente', true, 2),
  ('p2_g_34ed8946', 'Se buscan entradas en los dos sentidos; la vela de apertura no sesga el día', 'Se buscan entradas en los dos sentidos; la vela de apertura no sesga el día', 'plan', 'blanda', null, null, false, 148, null, false, 'siempre', array['R-27']::text[], 'plan_linea', 'guia', '🔴 Añadido 27/08/2026 · antes de enviar la orden', null, 'vigente', true, 2),
  ('p2_un_contrato', 'Opera siempre 1 contrato MNQ. El tamano no cambia por capital, racha ni conviccion.', 'Opera siempre 1 contrato MNQ. El tamano no cambia por capital, racha ni conviccion.', 'proceso', 'dura', 3, null, true, 4, 'auto', false, 'siempre', array['R-04']::text[], 'plan_regla', 'auto', 'Perímetro operativo', 'trades.qty = 1', 'vigente', true, 2),
  ('p2_ventana_horaria', 'Opera unicamente durante los 120 minutos siguientes a la apertura de la sesion americana.', 'Opera unicamente durante los 120 minutos siguientes a la apertura de la sesion americana.', 'proceso', 'dura', 3, null, true, 5, 'auto', false, 'siempre', array['R-02']::text[], 'plan_regla', 'auto', 'Perímetro operativo', 'trades.entry_time (Colombia) → ET entre 09:30 y 11:30', 'vigente', true, 2)
on conflict (codigo) do update set
  titulo = excluded.titulo,
  enunciado = excluded.enunciado,
  capa = excluded.capa,
  tipo = excluded.tipo,
  fase = excluded.fase,
  setup = excluded.setup,
  es_checklist = excluded.es_checklist,
  orden = excluded.orden,
  evidencia = excluded.evidencia,
  bloquea_go = excluded.bloquea_go,
  aplica_si = excluded.aplica_si,
  plan_reglas = excluded.plan_reglas,
  origen = excluded.origen,
  plan_tipo = excluded.plan_tipo,
  plan_bloque = excluded.plan_bloque,
  campo = excluded.campo,
  estado = excluded.estado,
  activa = excluded.activa,
  etapa = excluded.etapa,
  updated_at = now();

-- Lo que ya no está en el plan se desactiva (nunca se borra: su historial sigue contando).
update catalogo_reglas set activa = false, updated_at = now()
 where etapa = 2 and origen in ('plan_linea', 'plan_regla') and activa
   and codigo not in ('R-01', 'R-02', 'R-03', 'R-04', 'R-05', 'R-06', 'R-07', 'R-08', 'R-09', 'R-10', 'R-11', 'R-12', 'R-13', 'R-14', 'R-15', 'R-16', 'R-17', 'R-18', 'R-19', 'R-20', 'R-21', 'R-22', 'R-23', 'R-24', 'R-25', 'R-26', 'R-27', 'R-40', 'R-41', 'R-28', 'R-29', 'R-30', 'R-31', 'R-32', 'R-33', 'R-34', 'R-35', 'R-36', 'R-37', 'R-38', 'p2_g_7ca8fa6a', 'p2_g_56e12136', 'p2_g_c2fe2169', 'p2_g_3c6db45c', 'p2_g_d5a65697', 'p2_g_954acdc6', 'p2_g_f322eb01', 'p2_g_bdc4380f', 'p2_g_88dfc66e', 'p2_g_ad8984a6', 'p2_g_05dcd39d', 'p2_g_32e3a881', 'p2_g_509ccd8b', 'p2_g_882c476d', 'p2_corrida_fluida', 'p2_g_3891b80b', 'p2_g_a82d169d', 'p2_g_fad99fde', 'p2_stop_max', 'p2_g_9e2b60e5', 'p2_punto_referencia', 'p2_g_0525f6f2', 'p2_fomc_continuacion', 'p2_noticia', 'p2_g_8a5d31d2', 'p2_instrumento', 'p2_g_c214cf46', 'p2_g_ed59f89a', 'p2_g_ed096ec1', 'p2_g_3e1b11b1', 'p2_g_ec38f419', 'p2_g_32941671', 'p2_g_ab1071ef', 'p2_g_c71bf461', 'p2_g_9963d984', 'p2_g_218eb551', 'p2_una_operacion', 'p2_g_47bfb2ed', 'p2_g_411dcd27', 'p2_g_a2236380', 'p2_g_4d13fb5a', 'p2_g_2fbe48dc', 'p2_g_7e25f57a', 'p2_g_e84a5159', 'p2_g_609eb8eb', 'p2_g_230aec35', 'p2_g_52b219ac', 'p2_g_34ed8946', 'p2_un_contrato', 'p2_ventana_horaria');

update catalogo_reglas set activa = false, updated_at = now()
 where etapa = 1 and es_checklist and activa;

notify pgrst, 'reload schema';
