-- ─────────────────────────────────────────────────────────────────────────
-- Apex Tracker: cuentas de fondeo + registros diarios
-- Correr en Supabase SQL Editor
-- ─────────────────────────────────────────────────────────────────────────

-- Cuentas de evaluación / PA de Apex
create table if not exists apex_cuentas (
  id                  bigint generated by default as identity primary key,
  nombre              text not null,                -- ej: "Apex-11"
  numero_cuenta       text,                         -- ej: "APEX-232411-11"
  tamano              numeric not null default 50000,
  balance_inicial     numeric not null default 50000,
  drawdown_max        numeric not null default 2000,
  profit_target       numeric not null default 3000,   -- sobre el balance inicial → target = inicial + 3000
  safety_net_balance  numeric default 52100,           -- balance que congela el piso
  piso_congelado      numeric default 50100,           -- threshold fijo tras tocar safety net
  min_dias            int default 7,                   -- días mínimos de trading de la evaluación
  contratos_max       int,
  estado              text not null default 'evaluacion',
    -- evaluacion | recuperacion | critico | safety_net | aprobada | pa | quemada
  fecha_inicio        date,
  activa              boolean not null default true,
  notas               text,
  created_at          timestamptz default now()
);

-- Registro diario por cuenta
create table if not exists apex_registros (
  id          bigint generated by default as identity primary key,
  cuenta_id   bigint not null references apex_cuentas(id) on delete cascade,
  fecha       date not null,
  pnl_dia     numeric not null default 0,
  balance     numeric not null,            -- balance al cierre del día
  threshold   numeric not null,            -- threshold real (Rithmic) al cierre
  contratos   int,
  nota        text,
  created_at  timestamptz default now(),
  unique (cuenta_id, fecha)
);

-- Permisos para el rol anon (proyecto personal, RLS deshabilitado)
alter table apex_cuentas  disable row level security;
alter table apex_registros disable row level security;
grant select, insert, update, delete on apex_cuentas  to anon;
grant select, insert, update, delete on apex_registros to anon;
grant usage, select on all sequences in schema public to anon;

-- Datos iniciales: las 2 cuentas actuales
insert into apex_cuentas (nombre, numero_cuenta, estado, fecha_inicio, contratos_max, notas)
values
  ('Apex-11', 'APEX-232411-11', 'recuperacion', null, 3, 'Pérdida inicial -$1,600, luego 4 sesiones ganadoras'),
  ('Apex-12', 'APEX-232411-12', 'critico', null, 3, 'Balance por debajo del threshold — verificar en Rithmic');

-- Estado actual como primer registro (fecha de corte: hoy)
insert into apex_registros (cuenta_id, fecha, pnl_dia, balance, threshold, nota)
select id, current_date, 0, 49065, 48000, 'Estado inicial al crear el tracker'
from apex_cuentas where nombre = 'Apex-11';

insert into apex_registros (cuenta_id, fecha, pnl_dia, balance, threshold, nota)
select id, current_date, 0, 49160.52, 49176.01, 'Estado inicial al crear el tracker — pendiente verificación'
from apex_cuentas where nombre = 'Apex-12';
