-- Bitácora de backtesting: pasa de D1 (el portal) a Supabase (el Journal).
-- Fase 4a de docs/disenos/2026-09-24-unificacion-chaumer.md.
--
-- Mismo modelo que chaumer/04_Web/d1/0002 y 0003, traducido a Postgres:
--   · `numeric` en vez de `real`: el P&L está guardado en céntimos exactos y así sigue;
--   · `bt_cabecera.valor_punto` es nuevo: el portal lo sacaba de reglas.json al
--     compilar, y el Journal no puede leer ese archivo. Se siembra con el del plan
--     (valor_punto_MNQ = 2) y cada jornada lo congela, como hasta ahora.
--
-- Invariantes que viajan con las tablas (DISENO_BACKTESTING.md):
--   · `pnl` es NETO y se calcula AL GUARDAR: no se recalcula al mostrar;
--   · instrumento, contratos, valor_punto y comision se CONGELAN en cada jornada;
--   · `puntos` siempre en positivo: el signo lo pone `resultado`;
--   · `hora` en hora Colombia, hh:mm;
--   · un día sin operación es una jornada sin operaciones.
-- Nada de esto se mezcla con `trades` ni `apex_trades`: es backtesting, no dinero real.

create table if not exists bt_cabecera (
  id             smallint primary key default 1 check (id = 1),
  valor_inicial  numeric(12,2) not null default 0 check (valor_inicial >= 0),
  contratos      integer       not null default 1 check (contratos >= 1),
  instrumento    text          not null default 'MNQ',
  valor_punto    numeric(10,2) not null check (valor_punto > 0),
  comision       numeric(8,2)  not null default 0 check (comision >= 0),
  actualizada_en timestamptz   not null default now()
);

create table if not exists bt_jornadas (
  id             bigint generated by default as identity primary key,
  fecha          date          not null unique,
  instrumento    text          not null,
  contratos      integer       not null check (contratos >= 1),
  valor_punto    numeric(10,2) not null check (valor_punto > 0),
  comision       numeric(8,2)  not null default 0 check (comision >= 0),
  imagen         text,                          -- dirección de Cloudinary, o NULL
  notas          text,
  creada_en      timestamptz   not null default now(),
  actualizada_en timestamptz   not null default now()
);

create table if not exists bt_operaciones (
  id            bigint generated by default as identity primary key,
  jornada_id    bigint  not null references bt_jornadas(id) on delete cascade,
  orden         integer not null default 0,
  hora          text    not null check (hora ~ '^\d{2}:\d{2}$'),
  direccion     text    not null check (direccion in ('largo','corto')),
  setup         text    not null check (setup in ('continuacion','reingreso')),
  puntos        numeric(10,2) not null check (puntos >= 0),
  resultado     text    not null check (resultado in ('target','stop')),
  comision      numeric(8,2)  not null default 0 check (comision >= 0),
  pnl           numeric(12,2) not null,
  observaciones text
);

create index if not exists idx_bt_ops_jornada on bt_operaciones (jornada_id, orden);

comment on table bt_cabecera is
  'Backtesting: datos de inicio, fila única. PROPUESTA para la próxima jornada, no la verdad del pasado.';
comment on table bt_jornadas is
  'Backtesting: un día. instrumento/contratos/valor_punto/comision congelados al guardar. Sin operaciones = día sin entrada.';
comment on table bt_operaciones is
  'Backtesting: pnl NETO calculado al guardar (puntos×valor_punto×contratos, negativo si stop, menos comision). hora en Colombia.';

-- ── RLS ────────────────────────────────────────────────────────────────────
-- Misma política que las demás tablas: `anon` sin políticas, `authenticated`
-- todo, `service_role` ignora RLS.
alter table bt_cabecera    enable row level security;
alter table bt_jornadas    enable row level security;
alter table bt_operaciones enable row level security;

drop policy if exists auth_all on bt_cabecera;
create policy auth_all on bt_cabecera    for all to authenticated using (true) with check (true);
drop policy if exists auth_all on bt_jornadas;
create policy auth_all on bt_jornadas    for all to authenticated using (true) with check (true);
drop policy if exists auth_all on bt_operaciones;
create policy auth_all on bt_operaciones for all to authenticated using (true) with check (true);

grant select, insert, update, delete on bt_cabecera, bt_jornadas, bt_operaciones
  to authenticated, service_role;

-- ── La llave del portal ────────────────────────────────────────────────────
-- El portal (Cloudflare Pages) lee la bitácora desde su servidor con un JWT de
-- rol `portal_lector`. Ese rol solo puede leer las vistas `portal_*`: ni una
-- tabla, ni escribir. Sin login: solo se entra en él desde PostgREST, que hace
-- SET ROLE al rol del JWT (por eso se le concede a `authenticator`).
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'portal_lector') then
    create role portal_lector nologin noinherit;
  end if;
end $$;
grant portal_lector to authenticator;
grant usage on schema public to portal_lector;

-- Las vistas corren con los permisos de su dueño (no `security_invoker`): así
-- `portal_lector` lee las filas sin tener permiso sobre las tablas.
create or replace view portal_bt_cabecera as
  select valor_inicial, contratos, instrumento, valor_punto, comision
  from bt_cabecera;

-- Una fila por jornada, con sus operaciones en orden. Sin JOIN plano: una
-- jornada sin operaciones tiene que salir igual, con la lista vacía.
create or replace view portal_bt_jornadas as
  select j.id, j.fecha, j.instrumento, j.contratos, j.valor_punto, j.comision,
         j.imagen, j.notas, j.creada_en, j.actualizada_en,
         coalesce((
           select jsonb_agg(jsonb_build_object(
                    'id', o.id, 'orden', o.orden, 'hora', o.hora,
                    'direccion', o.direccion, 'setup', o.setup, 'puntos', o.puntos,
                    'resultado', o.resultado, 'comision', o.comision, 'pnl', o.pnl,
                    'observaciones', o.observaciones)
                  order by o.orden)
           from bt_operaciones o where o.jornada_id = j.id
         ), '[]'::jsonb) as operaciones
  from bt_jornadas j;

-- Supabase concede por defecto todo objeto nuevo de `public` a anon y
-- authenticated. En una vista que salta RLS eso sería una puerta abierta: fuera.
revoke all on portal_bt_cabecera, portal_bt_jornadas from anon, authenticated, public;
grant select on portal_bt_cabecera, portal_bt_jornadas to portal_lector, service_role;

notify pgrst, 'reload schema';
